import Purchases, { PERIOD_UNIT, PRODUCT_TYPE, PurchasesStoreProduct } from 'react-native-purchases';

export const productsMock: PurchasesStoreProduct[] = [
  {
    identifier: 'p-1',
    currencyCode: 'EUR',
    description: 'Unlimited access to Divizend companion.',
    // @ts-ignore
    defaultOption: {
      storeProductId: 'd-1',
      productId: 'subscription-1',
      id: 'op1',
      billingPeriod: { iso8601: 'P1M', unit: PERIOD_UNIT.MONTH, value: 1 },
      freePhase: null,
      isBasePlan: true,
      isPrepaid: true,
      tags: [],
      pricingPhases: [],
      fullPricePhase: null,
      installmentsInfo: null,
      introPhase: null,
      presentedOfferingContext: null,
    },
    discounts: [],
    introPrice: null,
    presentedOfferingContext: {
      offeringIdentifier: 'default',
      placementIdentifier: null,
      targetingContext: null,
    },
    price: 6.99,
    pricePerMonth: 6.99,
    pricePerMonthString: '6.99 €',
    priceString: '6.99 €',
    productCategory: Purchases.PRODUCT_CATEGORY.SUBSCRIPTION,
    productType: PRODUCT_TYPE.AUTO_RENEWABLE_SUBSCRIPTION,
    subscriptionPeriod: 'P1M',
    title: 'Monthly',
    pricePerWeek: 2,
    pricePerWeekString: '2',
    pricePerYear: 120,
    pricePerYearString: '120',
    subscriptionOptions: null,
  },
  {
    identifier: 'p-2',
    currencyCode: 'EUR',
    description: 'Unlimited access to Divizend companion for one year.',
    // @ts-ignore
    defaultOption: {
      storeProductId: 'd-2',
      productId: 'subscription-2',
      id: 'op2',
      billingPeriod: { iso8601: 'P1Y', unit: PERIOD_UNIT.YEAR, value: 1 },
      freePhase: null,
      isBasePlan: true,
      isPrepaid: true,
      tags: [],
      pricingPhases: [],
      fullPricePhase: null,
      installmentsInfo: null,
      introPhase: null,
      presentedOfferingContext: null,
    },
    discounts: [],
    introPrice: null,
    presentedOfferingContext: {
      offeringIdentifier: 'default',
      placementIdentifier: null,
      targetingContext: null,
    },
    price: 69.99,
    pricePerMonth: 5.83,
    pricePerMonthString: '5.83 €',
    priceString: '69.99 €',
    productCategory: Purchases.PRODUCT_CATEGORY.SUBSCRIPTION,
    productType: PRODUCT_TYPE.AUTO_RENEWABLE_SUBSCRIPTION,
    subscriptionPeriod: 'P1Y',
    title: 'Yearly',
    pricePerWeek: 1.35,
    pricePerWeekString: '1.35',
    pricePerYear: 69.99,
    pricePerYearString: '69.99',
    subscriptionOptions: null,
  },
];
